apiVersion: v1
kind: Service
metadata:
  name: {{ include "oarlock.fullname" . }}
  labels:
    {{- include "oarlock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oarlock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "oarlock.webComponent" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
